- README.md
- templates/_helpers.tpl
- templates/adminserver/adminserver-cm.yaml
- values.yaml
* Added support to declare the sslmode for an external database.
> Add support for sslmode on external databases.   Fixes #11

- Chart.yaml
- README.md
- values.yaml
1. Update readme to point out the master branch is not stable
2. Enable the persistence of Redis by default
3. Remove the image tag variable in values.yaml
> Update Harbor charts

- templates/chartmuseum/chartmuseum-dpl.yaml
- templates/registry/registry-dpl.yaml
the and operator was not taking affect for the deployment charts.
> correct order of 'and' operator

- templates/_helpers.tpl
- templates/ingress/ingress.yaml
- templates/portal/deployment.yaml
- templates/portal/service.yaml
- values.yaml
As we split ui into two parts: core and portal, this commit adds the portal to Harbor chart
> Add Harbor portal in chart

- README.md
- templates/adminserver/adminserver-dpl.yaml
- templates/chartmuseum/chartmuseum-dpl.yaml
- templates/clair/clair-dpl.yaml
- templates/jobservice/jobservice-dpl.yaml
- templates/notary/notary-server.yaml
- templates/notary/notary-signer.yaml
- templates/portal/deployment.yaml
- templates/registry/registry-dpl.yaml
- templates/ui/ui-dpl.yaml
- values.yaml
User can set the replicas for every components to control the num of instances when starting up Harbor
> Add replicas for the components in values.yaml

- README.md
- templates/adminserver/adminserver-cm.yaml
- templates/chartmuseum/chartmuseum-cm.yaml
- templates/chartmuseum/chartmuseum-dpl.yaml
- templates/chartmuseum/chartmuseum-pvc.yaml
- templates/chartmuseum/chartmuseum-secret.yaml
- templates/registry/registry-cm.yaml
- templates/registry/registry-dpl.yaml
- templates/registry/registry-pvc.yaml
- templates/registry/registry-secret.yaml
- values.yaml
This commits will allow users to configure the cloud storage for both registry and chartmuseum in values.yaml
> Support configuring cloud storage for chartmuseum

- templates/chartmuseum/chartmuseum-cm.yaml
> Fix #41, local storage for chartmuseum

- templates/core/core-dpl.yaml
- templates/database/database-ss.yaml
- values.yaml
Add "existingClaim" in database section to support to use the existing PVC
> Support to use existing PVC for database

- templates/ingress/ingress.yaml
Update the ingress rules according to the changes in https://github.com/goharbor/harbor/pull/5932
> Update the ingress rules

- templates/registry/registry-dpl.yaml
- templates/registry/registry-secret.yaml
This commit putting the same storage environment variables to the registry secret, and add it to both registry and registry controller
> Add storage configuration as environment variables to registry controller

- .helmignore
- templates/adminserver/adminserver-cm.yaml
- templates/chartmuseum/chartmuseum-cm.yaml
- templates/core/core-dpl.yaml
- templates/jobservice/jobservice-cm.yaml
- templates/notary/notary-cm.yaml
- templates/registry/registry-cm.yaml
- values.yaml
Support configuring log level for Harbor chart in values.yaml
> Add log level in values.yaml

- templates/jobservice/jobservice-cm.yaml
As the configuration of jobservice changed, this commit updates the configmap to do the corresponding updates
> Update configmap of jobservice

- templates/clair/clair-dpl.yaml
Apply the log level defined in values.yaml to Clair
> Add log level param to clair

- README.md
- docs/High Availability.md
- values.yaml
Update Readme and ha doc of Harbor chart
> Update docs of Harbor chart

- README.md
Add the link of upgrade guide in the readme
> Add upgrade guide link in the readme

- Chart.yaml
- values.yaml
This commit updates the following items:
1. Using the images version 1.7.0
2. Updates the chart version to 1.0.0
3. Updates the app version to 1.7.0
> Update images used by chart and versions in Chart.yaml

- templates/nginx/configmap-http.yaml
- templates/nginx/configmap-https.yaml
Signed-off-by: peimingming <peimingming@corp.netease.com>
[issue](https://github.com/goharbor/harbor-helm/issues/136)
> Fix download chart issue

- templates/nginx/configmap-http.yaml
- templates/nginx/configmap-https.yaml
Signed-off-by: peimingming <peimingming@corp.netease.com>
> Fix download chart issue in V1.0.0

- templates/clair/clair-svc.yaml
- templates/core/core-dpl.yaml
> Add environment variables needed by health check API

- requirements.lock
This commit deletes the file requirements.lock
> Remove the requirements.lock

- templates/core/core-cm.yaml
This commit changes the mode of core to dev to log more debug info
> Change mod to dev to log more info

- Chart.yaml
- values.yaml
> Bump up Harbor to 1.7.5

- templates/_helpers.tpl
Solution for issue #214
Encodes special characters in the password field for URL
> Escape (Encode) special characters in password for URL

- templates/database/database-ss.yaml
Wait a longer time to begin the probe to fix #145
> Wait a longer time to begin the probe to fix #145

- README.md
As we publishing the Harbor chart to a pubic chart repository, the doc needs to be updated
> Update the installation steps

- Chart.yaml
- values.yaml
Update chart version to 1.1.0 and update Harbor version to 1.8.0
> Update chart version to new release

- Chart.yaml
- values.yaml
Bump up Harbor version to 1.8.1
> Bump up Harbor version to 1.8.1

- README.md
- templates/nginx/service.yaml
- values.yaml
Added support for annotations and source IP address ranges against LoadBalancer type service
Signed-off-by: James Thompson <jst2120@gmail.com>
> Additional options with using expose type of LoadBalancer

- templates/ingress/ingress.yaml
> Set default backend when ingress controller is NCP

- values.yaml
> Bump up image version to v1.8.2-dev

- README.md
> Update README.md for new parameter - 1.1.0 branch

- Chart.yaml
- values.yaml
Bump up Harbor version to 1.8.2
> Bump up Harbor version to 1.8.2

- templates/core/core-dpl.yaml
- templates/database/database-ss.yaml
- templates/jobservice/jobservice-dpl.yaml
- templates/nginx/deployment.yaml
- templates/notary/notary-server.yaml
- templates/notary/notary-signer.yaml
- templates/portal/deployment.yaml
- templates/portal/service.yaml
- templates/redis/statefulset.yaml
Add security context and init containers to change permission of directory to allow the progress runs as non-root user
> Run as non-root user

- templates/nginx/configmap-http.yaml
- templates/nginx/configmap-https.yaml
- templates/nginx/deployment.yaml
- templates/nginx/service.yaml
Fix permission issue of nginx container
> Fix permission issue of nginx container

- Chart.yaml
- values.yaml
Bump up Harbor version to 1.8.3
> Bump up Harbor version to 1.8.3

- Chart.yaml
- values.yaml
> Release Harbor helm chart 1.2.0

- templates/nginx/configmap-https.yaml
This commit modifies the configmap of nginx, to make sure that when it's
serving https the secure flag is added to the cookie
> Add secure cookie flag

- templates/nginx/configmap-https.yaml
This commit modifies the configmap of nginx, to make sure that when it's
serving https the secure flag is added to the cookie
> Add secure cookie flag -- cherrypick to 1.2 branch

- .helmignore
- .travis.yml
- Chart.yaml
- test/install_helm.sh
- test/verify.sh
> Enable Travis CI to do the basic verification for PRs

- templates/nginx/configmap-http.yaml
- templates/nginx/configmap-https.yaml
> Add extra header for nginx

- Chart.yaml
- values.yaml
Bump up Harbor version to 1.8.4
> Bump up Harbor version to 1.8.4

- Chart.yaml
- values.yaml
Bump up Harbor version to 1.9.1
> Bump up Harbor version to 1.9.1

- templates/clair/clair-dpl.yaml
Add log level to Clair adapter
> Add log level to Clair adapter

- templates/_helpers.tpl
Fixes #390, add portal to no proxy setting
> Add portal to no proxy

- docs/High Availability.md
Use helm repo to download harbor chart
> Update installation part in HA document

- templates/core/core-cm.yaml
Add configuration options to configmap of core
> Add configuration options to configmap of core

- Chart.yaml
- values.yaml
Bump up Harbor version to 1.9.2
> Bump up Harbor version to 1.9.2

- Chart.yaml
- values.yaml
Bump up Harbor version to 1.8.5
> Bump up Harbor version to 1.8.5

- Chart.yaml
- values.yaml
> Bump up Harbor to 1.9.3

- Chart.yaml
- values.yaml
Bump up Harbor version to 1.8.6
> Bump up Harbor version to 1.8.6

- templates/nginx/deployment.yaml
Signed-off-by: Ankita Bhopatkar <ankita.bhopatkar@mendix.com>
> Upgrade kubernetes API version

- README.md
- docs/High Availability.md
> Add commands for helm3 in doc

- templates/chartmuseum/chartmuseum-dpl.yaml
- templates/clair/clair-dpl.yaml
- templates/registry/registry-dpl.yaml
> Add fsGroup for registry, chartmuseum and clair

- Chart.yaml
- values.yaml
Bump up Harbor version to 1.10.0
> Bump up Harbor version to 1.10.0

- Chart.yaml
- values.yaml
> Bump up to chart 1.2.4 and pin to harbor v1.9.4 inages

- templates/nginx/configmap-https.yaml
> Add missed '$' in nginx config map

- README.md
Fixes instructions on how to uninstall using helm3.
> FIX: Correct the uninstall command.

- Chart.yaml
- values.yaml
> Bump up Harbor Chart version to 1.3.1 with Harbor 1.10.1

- templates/nginx/configmap-http.yaml
- templates/nginx/configmap-https.yaml
> Add timestamp in nginx std out log message

- templates/nginx/configmap-http.yaml
- templates/nginx/configmap-https.yaml
> [Cherrypick - 1.3 ]Add timestamp in nginx std out log message

- templates/core/core-cm.yaml
- templates/core/core-dpl.yaml
- templates/jobservice/jobservice-cm-env.yaml
- templates/jobservice/jobservice-dpl.yaml
- templates/jobservice/jobservice-secrets.yaml
- templates/registry/registry-dpl.yaml
Update the evn of registry and controller URL used by core and jobservice
> Update the env of registry URL

- Chart.yaml
- values.yaml
> Bump version to 1.3.2

- index.yaml
> Upload the Harbor chart 1.3.2

- index.yaml
> Update harbor 1.3.2

- README.md
- templates/trivy/trivy-sts.yaml
- values.yaml
Signed-off-by: Daniel Pacak <pacak.daniel@gmail.com>
> feat(trivy): Add flag to skip verifying registry certificate

- templates/trivy/trivy-sts.yaml
1. Make trivy work when persistence.enable is false.
2. Make trivy work with exist PVC.
Closes #596, #598
> [Cherry pick]fix(trivy): make trivy work without persistence/with exist pvc

- templates/chartmuseum/chartmuseum-dpl.yaml
- templates/clair/clair-dpl.yaml
- templates/core/core-dpl.yaml
- templates/database/database-ss.yaml
- templates/jobservice/jobservice-dpl.yaml
- templates/nginx/deployment.yaml
- templates/notary/notary-server.yaml
- templates/notary/notary-signer.yaml
- templates/portal/deployment.yaml
- templates/redis/statefulset.yaml
- templates/registry/registry-dpl.yaml
- templates/trivy/trivy-sts.yaml
- values.yaml
Thanks to @alex1989hu for the fix!
Here the cherry-pick as requested by @ywk253100.
> Cherry-pick PR 573 and 610 to add serviceaccountname for each component

- templates/trivy/trivy-sts.yaml
Per https://github.com/goharbor/harbor-helm/pull/614#issuecomment-641876384
Ping @heww @ywk253100
> [Cherry pick]Add optional imagePullSecret to Trivy

- .github/workflows/integration.yaml
- .github/workflows/lint.yaml
- .github/workflows/unittest.yaml
> ci(lint): lint tasks with helm 2 and 3

- Chart.yaml
- values.yaml
> Bump up to 1.3.3 to consume Harbor OSS 1.10.3

- templates/internal/auto-tls.yaml
> fix(internal-tls): correct name for ca in the secret of chartmuseum

- docs/High Availability.md
- docs/Upgrade.md
- docs/_index.md
This will prepare the repo docs so they can be used to show Helm documentation on https://goharbor.io
Signed-off-by: Jonas Rosland <jrosland@vmware.com>
> Make changes to docs for inclusion on the website

- templates/internal/auto-tls.yaml
> [Cherry pick]fix(internal-tls): correct name for ca in the secret of chartmuseum

- Chart.yaml
- values.yaml
Bump up version to 1.4.1(Harbor version 2.0.1)
> Bump up version to 1.4.1(Harbor version 2.0.1)

- templates/registry/registry-cm.yaml
Replicate changes from:
https://github.com/goharbor/harbor/commit/aad63e7ae52e4c45ad4b08c5488e4b7d8867346b#diff-03197462f5cf29c980786d040f8bdfc3
to resolve push errors.
> Fixes #605: Enable Schema v2.1 compatibility

- templates/registry/registry-cm.yaml
Add "registry_config" item to the config file of registryctl
> Add "registry_config" item to the config file of registryctl

- Chart.yaml
- values.yaml
Bump up to 1.3.4(OSS Harbor 1.10.4)
> Bump up to 1.3.4(OSS Harbor 1.10.4)

- templates/trivy/trivy-sts.yaml
> Enable trivy subPath.

- values.yaml
Update the max open connection to 1000
> Update the max open connection to 1000

- Chart.yaml
- values.yaml
Bump up the image version to v2.0.2
> Bump up the image version to v2.0.2

- Chart.yaml
Update the broken icon link to the new one
> Update the broken icon link to the new one

- templates/trivy/trivy-sts.yaml
Signed-off-by: majian <46617237@qq.com>
> [Cherry-pick]Enable trivy subPath.

- templates/core/core-cm.yaml
- templates/core/core-secret.yaml
The changes of OSS Harbor: https://github.com/goharbor/harbor/pull/12539, https://github.com/goharbor/harbor/pull/12440, https://github.com/goharbor/harbor/pull/12383
Fixes #663
> Update the Harbor chart according to the changes of OSS Harbor

- templates/ingress/ingress.yaml
fixes #642
Authored-by: Bill Bean <wbean@pivotal.io>
> Fix issues encountered using ncp ingress controller

- templates/registry/registry-cm.yaml
> Add timeout to redis in registry config yml

- templates/registry/registry-cm.yaml
- values.yaml
Signed-off-by: Axel Goblet <axel.goblet@bigdatarepublic.nl>
> Fix #656: Allow S3 multipart upload config

- templates/core/core-cm.yaml
- templates/registry/registry-cm.yaml
> Make GC time window configuration, add redis password in registry config file

- templates/chartmuseum/chartmuseum-cm.yaml
- templates/chartmuseum/chartmuseum-dpl.yaml
- templates/clair/clair-dpl.yaml
- templates/core/core-dpl.yaml
- templates/jobservice/jobservice-cm.yaml
- templates/jobservice/jobservice-dpl.yaml
- templates/portal/configmap.yaml
- templates/portal/deployment.yaml
- templates/registry/registry-cm.yaml
- templates/registry/registry-dpl.yaml
- templates/trivy/trivy-sts.yaml
> refactor(internal-tls): mount internal tls with directory without subPath

- Chart.yaml
- values.yaml
Bump up Harbor version to 1.10.5
> Bump up Harbor version to 1.10.5

- .github/workflows/integration.yaml
- README.md
- templates/core/core-dpl.yaml
- values.yaml
> Add startup probe to harbor-core

- README.md
> Bump the the requirement for k8s version

- Chart.yaml
- values.yaml
Bump up Harbor version to 2.1.0
> Bump up Harbor version to 2.1.0

- templates/registry/registry-cm.yaml
- values.yaml
> [cherry-pick]s3 storage allow to skip verify

- Chart.yaml
- values.yaml
Bump up OSS Harbor version to 2.0.3
> Bump up OSS Harbor version to 2.0.3

- Chart.yaml
- values.yaml
> Bump up OSS Harbor to 2.1.1

- templates/chartmuseum/chartmuseum-dpl.yaml
- templates/clair/clair-dpl.yaml
- templates/core/core-dpl.yaml
- templates/database/database-ss.yaml
- templates/jobservice/jobservice-dpl.yaml
- templates/nginx/deployment.yaml
- templates/notary/notary-server.yaml
- templates/notary/notary-signer.yaml
- templates/portal/deployment.yaml
- templates/redis/statefulset.yaml
- templates/registry/registry-dpl.yaml
- templates/trivy/trivy-sts.yaml
Add support to run in the restricted psp enabled k8s
> Add support to run in the restricted psp enabled k8s

- Chart.yaml
- values.yaml
> Bump up OSS Harbor to 1.10.6

- Chart.yaml
- values.yaml
> Bump up OSS Harbor to 2.0.4

- Chart.yaml
- values.yaml
> Bump up OSS Harbor to v2.0.5

- Chart.yaml
- values.yaml
> Bump up OSS Harbor to v2.1.2

- templates/portal/service.yaml
> templates/portal: set service type NodePort on gce

- Chart.yaml
- values.yaml
> Bump up OSS Harbor to v2.1.3

- templates/database/database-ss.yaml
> Migrate the data of postgres into a sub folder

- templates/notary/notary-secret.yaml
Add SAN to the certificate of notary singer
Fixes #835
> Add SAN to the certificate of notary singer

- .github/workflows/integration.yaml
- README.md
Update the kubernetes version used in CI
> Update the kubernetes version used in CI

- templates/jobservice/jobservice-cm.yaml
- templates/jobservice/jobservice-dpl.yaml
- templates/jobservice/jobservice-pvc.yaml
- values.yaml
Support specify multiple job loggers for jobservice
Fixes #680
> Support specify multiple job loggers for jobservice

- Chart.yaml
- values.yaml
> Bump up OSS Harbor to 2.0.6

- Chart.yaml
- values.yaml
> Bump up OSS Harbor to 2.2.0

- templates/registry/registry-dpl.yaml
Add environment variables of http proxy into registryctl container. #861
> Add http proxy to registryctl container

- templates/database/database-ss.yaml
> Add another init container for database to ensure the permission of data directory

- Chart.yaml
- templates/chartmuseum/chartmuseum-dpl.yaml
- templates/clair/clair-dpl.yaml
- templates/core/core-dpl.yaml
- templates/database/database-ss.yaml
- templates/jobservice/jobservice-dpl.yaml
- templates/nginx/deployment.yaml
- templates/notary/notary-server.yaml
- templates/notary/notary-signer.yaml
- templates/portal/deployment.yaml
- templates/redis/statefulset.yaml
- templates/registry/registry-dpl.yaml
- templates/trivy/trivy-sts.yaml
- values.yaml
Backport the PSP support fixes and bump up OSS Harbor to 2.1.4
> Backport the PSP support fixes and bump up OSS Harbor to 2.1.4

- Chart.yaml
- values.yaml
> Bump up OSS Harbor to 2.2.1

- README.md
- templates/nginx/service.yaml
- values.yaml
> Add annotations to clusterIP service

- templates/nginx/configmap-http.yaml
- templates/nginx/configmap-https.yaml
- templates/portal/configmap.yaml
> Add ipv6 support for nginx

- templates/registry/registry-dpl.yaml
Signed-off-by: yamashita <yamashita@valinux.co.jp>
> [cherry-pick]Add http proxy to registryctl container

- .helmignore
- Chart.yaml
- templates/ingress/ingress.yaml
- values.yaml
Fixes https://github.com/goharbor/harbor-helm/issues/918
> Bump up OSS Harbor to v2.1.5

- values.yaml
Signed-off-by: Diogo Guerra <diogo.filipe.tomas.guerra@cern.ch>
> Clarify max{Open/Idle}Conns

- Chart.yaml
- values.yaml
> Bump up to OSS Harbor v2.2.2

- templates/exporter/exporter-cm-env.yaml
- templates/exporter/exporter-dpl.yaml
- values.yaml
1. cert issue when internal TLS enabled
2. add config for job service monitoring
> Fix exporter can not start issue

- templates/registry/registry-dpl.yaml
- templates/registry/registry-secret.yaml
> store the file htpasswd in a separate secret

- templates/exporter/exporter-dpl.yaml
Exporter Cert not exist when internal TLS enabled
> Fix exporter cert issue #909 and #894

- templates/notary/notary-server.yaml
- templates/notary/notary-signer.yaml
Add probes for notary service
Fixes #847
> Add probes for notary service

- Chart.yaml
- values.yaml
> Bump OSS Harbor to 1.10.7

- templates/jobservice/jobservice-cm-env.yaml
- templates/jobservice/jobservice-cm.yaml
- templates/jobservice/jobservice-svc.yaml
- values.yaml
> Add metrcis for harbor jobservice

- test/e2e/Dockerfile
- test/e2e/Jenkinsfile
Introduce the pipeline to run the e2e testing based on the jenkins shared library
> Introduce the pipeline to run the e2e testing

- templates/nginx/configmap-http.yaml
- templates/nginx/configmap-https.yaml
- templates/registry/registry-cm.yaml
- values.yaml
> Do the corresponding changes according to OSS Harbor to improve the performance

- Chart.yaml
- test/e2e/Jenkinsfile
- values.yaml
> Bump up version to 1.7.0

- Chart.yaml
- values.yaml
> Bump up version to 1.3.8

- .github/workflows/integration.yaml
- Chart.yaml
- values.yaml
> Bump up OSS Harbor to 2.2.3

- .github/workflows/integration.yaml
- Chart.yaml
- values.yaml
> Bump up OSS Harbor to v2.1.6

- docs/Upgrade.md
Update the upgrade documentation to provide the workaroud for issue #987
> Update the upgrade documentatin

- Chart.yaml
- values.yaml
> Bump up version to 1.7.1

- templates/chartmuseum/chartmuseum-cm.yaml
- values.yaml
Set this number can as a workaround for #1026
> Make chartmuseum index limit configurable

- .github/workflows/integration.yaml
> Add debug info for helm action pipeline

- Chart.yaml
- values.yaml
> Bump up version to 1.7.2

- Chart.yaml
- values.yaml
> Bump up to Harbor v2.3.3

- Chart.yaml
- values.yaml
> Bump up to OSS Harbor 2.4.0

- Chart.yaml
- values.yaml
> Bump up version to 1.7.4

- templates/ingress/ingress.yaml
- values.yaml
should allow ingress class resource to work for nginx ingress 👍
> add className

- Chart.yaml
- values.yaml
> Bump up version to 1.7.5

- Chart.yaml
- values.yaml
> Bump up version to 1.8.1

- Chart.yaml
- values.yaml
> Bump up version to 1.3.10, appVersion 1.10.10

- Chart.yaml
- values.yaml
> Bump up version to 1.8.2

- Chart.yaml
> fix: update maintainer list

- Chart.yaml
- test/e2e/Jenkinsfile
- values.yaml
> Bump up version to 1.9.0

- CONTRIBUTING.md
Signed-off-by: Tom OBrien <tom.obrien@ns.nl>
> Fix link to contributing guide

- Chart.yaml
- values.yaml
> Bump up version to 1.3.11-rc1, appVersion 1.10.11-rc1

- Chart.yaml
- values.yaml
> Bump up version to 1.3.11, appVersion 1.10.11

- Chart.yaml
- values.yaml
> Bump up version to 1.9.1

- Chart.yaml
- values.yaml
> Bump up version to 1.9.2

- test/e2e/Dockerfile
> perf: upgrade kubectl version to v1.21.1, helm version to v3.9.2

- Chart.yaml
- values.yaml
> Bump up version to 1.3.12-rc1, appVersion 1.10.12-rc1

- Chart.yaml
- values.yaml
> Bump up version to 1.8.3, appVersion to 2.4.3

- Chart.yaml
- values.yaml
> Bump up version to 1.3.12, appVersion 1.10.12

- templates/nginx/configmap-https.yaml
> fix: remove TLSv1.1 from ssl_protocols

- Chart.yaml
- values.yaml
> Bump up version to 1.3.13, appVersion 1.10.13

- Chart.yaml
- values.yaml
> Bump up version to 1.9.4, appVersion to 2.5.4

- templates/nginx/configmap-https.yaml
> Remove ssl_protocols TLSv1.1

- templates/portal/configmap.yaml
update made alone with upstream changes 
https://github.com/goharbor/harbor/issues/17495
> update portal configMap of swagger

- templates/registry/registry-dpl.yaml
Signed-off-by: Aleksy Zalenski <aleksy.zalenski@branch.io>
> [Cherry-pick] - Fix existing secret ref

- templates/_helpers.tpl
https://github.com/goharbor/harbor-helm/issues/1296
> fix external redis url

- templates/_helpers.tpl
> [cherry-pick]remove default username redis in external redis url

- Chart.yaml
- values.yaml
> Bump up version to 1.3.14-rc1, appVersion 1.10.14-rc1

- templates/core/core-pre-upgrade-job.yaml
Add secret env to job when database external secret is used
Fix #1300 
Signed-off-by: Cong Ha Minh <conghm1@viettel.com.vn>
> Fix Helm Database Migration Job

- Chart.yaml
- values.yaml
> Bump up version to 1.3.14-rc2, appVersion 1.10.14-rc2

- Chart.yaml
- values.yaml
> Bump up version to 1.3.14, appVersion 1.10.14

- Chart.yaml
- values.yaml
> Bump up version to 1.10.1, appVersion to 2.6.1

- Chart.yaml
- values.yaml
> Bump up version to 1.10.2, appVersion to 2.6.2

- Chart.yaml
- values.yaml
> Bump up version to 1.3.15, appVersion 1.10.15

- Chart.yaml
- test/e2e/Jenkinsfile
- values.yaml
> Bump up version to 1.11.0, appVersion to 2.7.0

- Chart.yaml
- values.yaml
> Bump up version to 1.10.3, appVersion to 2.6.3

- Chart.yaml
- values.yaml
> Bump up version to 1.9.5, appVersion to 2.5.5

- Chart.yaml
- values.yaml
> Bump up version to 1.3.16-rc1, appVersion 1.10.16-rc1

- Chart.yaml
- values.yaml
> Bump up version to 1.3.16, appVersion 1.10.16

- templates/core/core-dpl.yaml
- templates/database/database-ss.yaml
- templates/exporter/exporter-dpl.yaml
- templates/jobservice/jobservice-dpl.yaml
- templates/nginx/deployment.yaml
- templates/notary/notary-server.yaml
- templates/notary/notary-signer.yaml
- templates/portal/deployment.yaml
- templates/redis/statefulset.yaml
- templates/registry/registry-dpl.yaml
- templates/trivy/trivy-sts.yaml
- values.yaml
> feat: add podLabels

- templates/exporter/exporter-dpl.yaml
Fixes:  https://github.com/goharbor/harbor-helm/issues/1527
> Add tls checksum  to exporter deployment

- test/e2e/Jenkinsfile
cherry-pick of this PR: 
* https://github.com/goharbor/harbor-helm/pull/1548
> [Cherry-pick] fix: get ingressControllerIP based on ingressControllerServiceType

- values.yaml
This updates the external documentation links in the values.yaml to the current repos and branches. Please let me know if you'd like me to bump the chart version as well.
Thanks!
> Update values.yaml - update old doc link references in comments

- templates/_helpers.tpl
> fix: single qoutes for trace attributes

- values.yaml
> fix: add clusterIP.ports.httpsPort back

- values.yaml
> [Cherry-pick] fix: add clusterIP.ports.httpsPort back

- templates/_helpers.tpl
cherry-pick of this PR: https://github.com/goharbor/harbor-helm/pull/1561
> [Cherry-pick] fix: single qoutes for trace attributes

- templates/_helpers.tpl
fix: https://github.com/goharbor/harbor/issues/19387
> fix external redis existing secret url render

- templates/core/core-cm.yaml
Fix: https://github.com/goharbor/harbor-helm/issues/1642
> fix: quote for ARTIFACT_PULL_ASYNC_FLUSH_DURATION

- templates/core/core-cm.yaml
> fix quote for ARTIFACT_PULL_ASYNC_FLUSH_DURATION

- templates/registry/registry-dpl.yaml
Fix: https://github.com/goharbor/harbor-helm/issues/1644
> fix: add REGISTRY_HTTP_SECRET env for registry if .Values.registry.existingSecret is set

- values.yaml
1, place all the components settings at the bottom. 
2, Ensure uniform styling across all components.
> unify the components settings

- .github/workflows/integration.yaml
bump the version of ingress nginx
> upgrade ingress

- templates/ingress/ingress.yaml
fix: https://github.com/goharbor/harbor-helm/issues/1850
> remove chart repo path from ingress template

- templates/_helpers.tpl
- templates/registry/registry-cm.yaml
- test/unittest/core/core_configmap_test.yaml
- values.yaml
fix:
https://github.com/goharbor/harbor/issues/21633
> rendering config for redis tls

- templates/nginx/configmap-https.yaml
fix: https://github.com/goharbor/harbor-helm/issues/2199
> add proxy timeout for nginx https config
