goharbor/harbor-helm

templates/ingress/ingress.yaml

如果我设置了 notary.enabled=false ，ingress 会创建这个不存在的 service ，添加这个属性的可选。
``` bash
helm install \
--name="registry" \
--set="externalDomain=registry.clelo.org" \
--set="notary.enabled=false" \
.
```
会创建一个  notary-registry.clelo.org 的域名。
Signed-off-by: MingLe Lan lanmingle@qq.com

add notary ingress option support

---

CONTRIBUTING.md
Chart.yaml
README.md
templates/NOTES.txt
templates/clair/clair-svc.yaml

This commit removes the keyword "vmware" from the content of files

Remove the "vmware" from files

---

README.md
templates/adminserver/adminserver-dpl.yaml
templates/chartmuseum/chartmuseum-dpl.yaml
templates/chartmuseum/chartmuseum-pvc.yaml
templates/registry/registry-dpl.yaml
templates/registry/registry-pvc.yaml
values.yaml

The components: adminserver, registry and chartmuseum are all stateless applications, so the Deployment should be used in the chart.

Using Deployment rather than StatefulSet for adminserver, registry and chartmuseum

---

templates/clair/clair-cm.yaml
values.yaml

Users can set the values of clair.updatersInterval in values.yaml to configure the updater interval

Make Clair updater interval configurable in chart

---

README.md
templates/NOTES.txt
templates/_helpers.tpl
templates/adminserver/adminserver-cm.yaml
templates/ingress/ingress.yaml
templates/ingress/secret.yaml
templates/notary/notary-cm.yaml
templates/registry/registry-cm.yaml
templates/ui/ui-dpl.yaml
values.yaml

The externalDomain is used to generate the ingress rule, but in the scenario that another proxy is deployed before Harbor, the externalDomain should be configured as the domain of external proxy and it should not be used to generate the ingress rule.

Separate the ingress rule host and "externalDomain" in values.yaml

---

templates/ingress/ingress.yaml

The "hosts" is needed in some old versions of nginx ingress controller

Add hosts in tls of ingress

---

templates/database/database-ss.yaml

* Allows for disconnected/offline installs
Cannot currently install harbor from an offline harbor repository without access to pull upstream container 'busybox:1.25.0' (or pre-caching same on hosts)
* Removes dependency on static busybox version
'busybox:1.25.0' is a two year old image with published vulnerabilities resolve in newer versions.  Image should be templated and either default to an existing harbor container to reduce attack surface, or updated to default to a newer busybox.
* Reuses existing harbor database container by default
As init container is only executing `rm`, the existing database image should suffice for the init container, reducing the number of required images.

Template database init container image

---

README.md
templates/adminserver/adminserver-dpl.yaml
templates/chartmuseum/chartmuseum-dpl.yaml
templates/clair/clair-dpl.yaml
templates/database/database-ss.yaml
templates/jobservice/jobservice-dpl.yaml
templates/notary/notary-server.yaml
templates/notary/notary-signer.yaml
templates/portal/deployment.yaml
templates/registry/registry-dpl.yaml
templates/ui/ui-dpl.yaml
values.yaml

The yaml anchor can not work as expected when setting values by "helm --set", so remove the anchor and keep only one global key to set the image pull policy

Keep only a single image pull policy for all images

---

README.md
templates/jobservice/jobservice-dpl.yaml
templates/jobservice/jobservice-pvc.yaml
values.yaml

Currently, the logs of jobservice are stored in an emptyDir volume, this commit adds a PVC for it

Add PVC to jobservice

---

README.md
templates/ingress/ingress.yaml
values.yaml

Currently this helm chart only creates one ingress resource and shares the same TLS secret. 
This splits the two services into their own ingress resource and allows users to use a different secret.
To expect the same behavior, the default is to use the same value as what is set in `ingress.tls.secretName`

Create separate ingress resource for notary

---

README.md
requirements.yaml
templates/_helpers.tpl
templates/chartmuseum/chartmuseum-cm.yaml
templates/chartmuseum/chartmuseum-secret.yaml
templates/redis/service.yaml
templates/redis/statefulset.yaml
templates/registry/registry-cm.yaml
values.yaml

If Redis specified in requirement.yaml will be deployed even though users use an external Redis, this commit removes the dependency and use the one of Harbor own. In this way, we can controll the Redis through template.

Remove the dependency chart for Redis and use the one of Harbor own

---

README.md
templates/chartmuseum/chartmuseum-dpl.yaml
templates/chartmuseum/chartmuseum-pvc.yaml
templates/database/database-ss.yaml
templates/jobservice/jobservice-dpl.yaml
templates/jobservice/jobservice-pvc.yaml
templates/redis/statefulset.yaml
templates/registry/registry-dpl.yaml
templates/registry/registry-pvc.yaml
values.yaml

1. The "subPath" specifies the directory used inside PVC
2. The "resourcePolicy" is used to avoid removing PVCs during a helm delete operation

Add "subPath" and "resourcePolicy"

---

templates/_helpers.tpl
templates/adminserver/adminserver-dpl.yaml
templates/chartmuseum/chartmuseum-dpl.yaml
templates/clair/clair-dpl.yaml
templates/core/core-dpl.yaml
templates/database/database-ss.yaml
templates/jobservice/jobservice-dpl.yaml
templates/notary/notary-server.yaml
templates/notary/notary-signer.yaml
templates/portal/deployment.yaml
templates/redis/statefulset.yaml
templates/registry/registry-dpl.yaml

1. Upgrade the Kubernetes API versions to the latest stable ones
2. Remove the mutable label for helm release upgrade, related issue: https://github.com/helm/charts/issues/7680

Upgrade Kubernetes API version and remove the mutable label for upgrade

---

templates/chartmuseum/chartmuseum-dpl.yaml
templates/registry/registry-dpl.yaml

When the persistence is disabled, use the emptyDir as the volume for registry and chartmuseum to fix permission deny issue when pushing images.

Use emtpyDir as volume for registry and chartmuseum

---

README.md
templates/adminserver/adminserver-cm.yaml
templates/clair/clair-dpl.yaml
templates/jobservice/jobservice-dpl.yaml
templates/registry/registry-cm.yaml
templates/registry/registry-dpl.yaml
templates/registry/registry-pvc.yaml
templates/registry/registry-secret.yaml
templates/registry/registry-svc.yaml
values.yaml

Use an http(s) proxy to update vulnerabilities database from internet if clair container is behind corporate proxies.

Proxy for clair

---

values.yaml

Change the access mode of volumes for jobservice, registry and chartmuseum: ReadWriteOnce -> ReadWriteMany

Change access mode of volumes

---

.helmignore

Some useless files, such as .git, docs/*, will be uploaded to tiller when deploying Harbor chart, this will cause error https://github.com/helm/helm/issues/1996. The helmignore can be used to ignore these files

[0.3.0]Add helmignore to avoid uploading useless files to tiller when deploying chart

---

README.md
docs/High Availability.md
templates/adminserver/adminserver-dpl.yaml
templates/chartmuseum/chartmuseum-dpl.yaml
templates/clair/clair-dpl.yaml
templates/core/core-dpl.yaml
templates/database/database-ss.yaml
templates/jobservice/jobservice-dpl.yaml
templates/nginx/deployment.yaml
templates/notary/notary-server.yaml
templates/notary/notary-signer.yaml
templates/registry/registry-dpl.yaml
values.yaml

1. Empty the "subPath" for volumes
2. Set "ReadWriteOnce" as the default value of access mode
3. Add checksum annotation for pod, see #5193 for detail

Update Harbor chart according to the requirement for upgrade

---

values.yaml

Due to the bug of helm https://github.com/helm/helm/issues/1707, the chunksize will be rendered in scientific notation. Quote it to avoid this.

Quote the chunksize to avoid the helm bug

---

README.md
templates/adminserver/adminserver-dpl.yaml
templates/chartmuseum/chartmuseum-dpl.yaml
templates/clair/clair-dpl.yaml
templates/core/core-dpl.yaml
templates/database/database-ss.yaml
templates/jobservice/jobservice-dpl.yaml
templates/nginx/deployment.yaml
templates/notary/notary-server.yaml
templates/portal/deployment.yaml
templates/redis/statefulset.yaml
templates/registry/registry-dpl.yaml
values.yaml

Allow annotations to be added to pods
We use [kiam](https://github.com/uswitch/kiam) to managing access to AWS, and it requires annotating pods with the role they should assume. In order to use S3 as a backend, we need this annotation added.
This should help with other use cases as well

Add support for customizing pod annotations

---

templates/ingress/ingress.yaml
values.yaml

When deploying chart by passing only "ingress.tls.secretName" in "--set", the notary service will use the generated certificate rather than using the same one with core service, this commit fixes this.

Use the same certificate for both core and notary service

---

templates/chartmuseum/chartmuseum-cm.yaml

Pass the context "." as a param in calling "tempalte" function

[0.3.0]Fix bug in the configmap of chartmuseum

---

README.md
templates/registry/registry-cm.yaml
values.yaml

When using `s3` for the backend type, `docker push` cannot successfully push the image, and will always be `retrying`.
If switch the backend to `filesystem`, this issue was gone.
Adding the following to the registry config.yml manually fixes my issue.
```yaml
storage:
redirect:
disable: true
```
And thanks for @rizwan-kh  helping!!
issue links:
https://github.com/goharbor/harbor/issues/5240
https://github.com/vmware/harbor-boshrelease/issues/15

Fix s3 backend push retrying issue

---

templates/chartmuseum/chartmuseum-dpl.yaml
templates/core/core-dpl.yaml
templates/jobservice/jobservice-dpl.yaml
templates/notary/notary-server.yaml
templates/registry/registry-dpl.yaml

Chartmuseum depends on core secret, using the env `BASIC_AUTH_PASS` from `harbor.core` secret.
This change adds a checksum on the chartmuseum deployment to force the recreation of the pods, allowing them to get the new value for the env variable.

Add checksum in chartmuseum to core secret

---

templates/chartmuseum/chartmuseum-cm.yaml

Issue #149 
Chart Museum is not configured with a `CHART_URL` which results in it returning relative URLs in the index:
```
harbor:
- appVersion: 1.7.0
home: https://goharbor.io
....
urls:
- charts/harbor-1.7.0.tgz
version: 1.7.0
```
This causes issues for some tools that expect a URL.
I went with always setting the `CHART_URL` based on the `externalURL` value. The alternative would be to introduce a new key for the CHART_URL that defaults to empty and preserves the existing relative URL behavior.
The downside of using `externalURL` is that it may cause upgrade issues due to a bug in chart museum: https://github.com/helm/chartmuseum/issues/157 . Chart Museum does not rewrite the cache when the `CHART_URL` changes, which means upgrading the chart will cause the index to return relative for …

Configure CHART_URL for chart museum

---

templates/chartmuseum/chartmuseum-cm.yaml

Reverts #150
The PR #150 causes new issue: [goharbor/harbor#6903](https://github.com/goharbor/harbor/issues/6903).
Harbor doesn't support conifgure chart_url fow now, there is an issue [goharbor/harbor#6572](https://github.com/goharbor/harbor/issues/6572) to track this. After the issue is fixed, we can add the support in chart

Reverts #150

---

templates/registry/registry-cm.yaml

Disable validation for registry to fix Docker registry not working with Windows layers.
See docker/distribution#2795 for more details.

Disable validation for registry

---

templates/_helpers.tpl
templates/common/certificate-secret.yaml
values.yaml

This commit makes the secret name used by Harbor empty by default

Bug fix: empty the secret name used by Harbor

---

templates/registry/registry-cm.yaml
templates/registry/registry-secret.yaml

The Redis password belongs with other passwords, in the registry secret, instead of in the registry configmap.

Place the redis password in the registry secret not the configmap.

---

templates/chartmuseum/chartmuseum-cm.yaml

This sets proper default values for TLS_CERT and TLS_KEY in the
Chartmuseum ConfigMap.
Closes #192
Signed-off-by: Dan Norris <dan.norris@netapp.com>

Set default values for TLS_CERT and TLS_KEY in the Chartmuseum ConfigMap

---

templates/core/core-cm.yaml

Relates to #226
When installing harbor-helm `v1.1.0` the following error appears on the core container:
```
$ kubectl logs harbor-devl-harbor-core-5ddf5ff597-mqg8w -c core -f                                                                                                                     
2019-05-31T12:00:16Z [INFO] [/replication/adapter/harbor/adapter.go:41]: the factory for adapter harbor registered                                                                                                 
2019-05-31T12:00:16Z [INFO] [/replication/adapter/dockerhub/adapter.go:24]: Factory for adapter docker-hub registered                                                                                              
2019-05-31T12:00:16Z [INFO] [/replication/adapter/native/adapter.go:30]: the …
```

Setup missing ADMIRAL_URL config on core

---

templates/nginx/deployment.yaml

Currently the `nginx.replicas` option specified in the `values.yaml` file isn't used in the deployment for NGINX.
With this change the replica count from the `values.yaml` is used in the NGINX deployment.

Add replicas option to NGINX deployment

---

templates/nginx/service.yaml
values.yaml

This commit add the IP field to expose.loadBalancer, which will be set
to the service of nginx pod

Allow setting IP for loadBalancer  -- 1.1 branch

---

templates/notary/notary-cm.yaml
templates/notary/notary-secret.yaml
templates/notary/notary-server.yaml
templates/notary/notary-signer.yaml

Fixes #243 
- Store automatically generated notary certificates in a k8s secret for better security
- Unify notary certificate mount templating, for reduced complexity in notary-cm.yaml, notary-server.yaml and notary-signer.yaml

Generated notary certificates in secret instead of configmap

---

templates/nginx/deployment.yaml

Helm <= 2.10 doesn't support the assignment of a value to a variable defined in a different scope, refactor the logic to support the helm client whose version <= 2.10

Refactor the assignment logic to support old version of helm

---

templates/registry/registry-dpl.yaml

Garbage collector got 500 error when using GCS to store image. The reason is because missing mount for gcs-key.json so this PR is an attempt to fix it.

Fix GC 500 error when using with imageChartStorage 'gcs'

---

templates/registry/registry-cm.yaml
values.yaml

Add a value to config relativeurls support on registry. This is needed when expose.type is not set to ingress to avoid "unkown blob" error on image push.
Resolves #174

add registry.relativeurls value

---

templates/core/core-cm.yaml
templates/core/core-dpl.yaml

Fixes #378, mount the certificate of UAA in a seperated directory

[Cherry-pick]Mount the certificate of UAA in a seperated directory

---

conf/clair.yaml

This commit make remove notifier from configuration file of clair in the chart to
make sure it's consistent with Harbor 1.9

Remove notifier section from clair conf file - cherrypick to 1.2 branch

---

conf/clair.yaml

This commit make remove notifier from configuration file of clair in the chart to
make sure it's consistent with Harbor 1.9

Remove notifier section from clair conf file

---

templates/core/core-cm.yaml
templates/core/core-dpl.yaml

Fixes #378, mount the certificate of UAA in a seperated directory

Mount the certificate of UAA in a seperated directory

---

templates/database/database-ss.yaml

Add sub path when mounting the volume for database init container

Add sub path when mounting the volume for database init container

---

templates/database/database-ss.yaml

Add sub path when mounting the volume for database init container

[Cherry-pick]Add sub path when mounting the volume for database init container

---

templates/chartmuseum/chartmuseum-dpl.yaml
templates/clair/clair-dpl.yaml
templates/database/database-ss.yaml
templates/jobservice/jobservice-dpl.yaml
templates/nginx/deployment.yaml
templates/portal/deployment.yaml
templates/redis/statefulset.yaml
templates/registry/registry-dpl.yaml

This commits extends the initialDelaySeconds of livenessProbe to avoild pod creating failure when the pod starting up slowly

Extend the initialDelaySeconds of livenessProbe

---

templates/chartmuseum/chartmuseum-dpl.yaml
templates/clair/clair-dpl.yaml
templates/database/database-ss.yaml
templates/jobservice/jobservice-dpl.yaml
templates/nginx/deployment.yaml
templates/portal/deployment.yaml
templates/redis/statefulset.yaml
templates/registry/registry-dpl.yaml

This commits extends the initialDelaySeconds of livenessProbe to avoild pod creating failure when the pod starting up slowly

[Cherry-pick-1.2]Extend the initialDelaySeconds of livenessProbe

---

templates/chartmuseum/chartmuseum-dpl.yaml
templates/clair/clair-dpl.yaml
templates/database/database-ss.yaml
templates/jobservice/jobservice-dpl.yaml
templates/nginx/deployment.yaml
templates/portal/deployment.yaml
templates/redis/statefulset.yaml
templates/registry/registry-dpl.yaml

This commits extends the initialDelaySeconds of livenessProbe to avoild pod creating failure when the pod starting up slowly

[Cherry-pick-1.1]Extend the initialDelaySeconds of livenessProbe

---

README.md

Editing`{}}` to `{}` for the default annotation value.

Removing typo '}' from ingress.annotations default

---

templates/registry/registry-cm.yaml

The "ignoredmediatypes" ignores several notifications sent by registry

Add "ignoredmediatypes" to config.yml of registry

---

values.yaml

This commit makes sure we can run ci on pipeline to verify latest code
on 1.9 branch.

Update the image tags to 1.9.4-dev for chart 1.2.x

---

templates/nginx/configmap-https.yaml

Add missed '$' in nginx config map - cherrypick 1.2

---

templates/nginx/configmap-https.yaml

Add missed '$' in nginx config map -cherrypick 1.3

---

templates/trivy/trivy-secret.yaml
values.yaml

We have to encode the token, otherwise it's get decoded to gibberish and fails when Trivy downloads the DB form GitHub.

fix(trivy): Encode GitHub token

---

templates/trivy/trivy-sts.yaml

Do not generate Trivy StatefulSet if it is not enabled
Fixes #545
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>

Check trivy.enabled in statefulset

---

templates/chartmuseum/chartmuseum-cm.yaml
templates/registry/registry-cm.yaml

This commit adds support for AWS S3 SSE for registry and chartmuseum. It's already defined in values file (see "keyid").

add support for AWS S3 Server Side Encryption

---

README.md

I hope this is correct. It sounded a little bit weird for me, if the resource is called `httpsPort` but the description says `HTTP` port.

fix expose.loadBalancer.ports.httpsPort in README

---

templates/_helpers.tpl
templates/trivy/trivy-sts.yaml
values.yaml

Without that option Core will not able to reach Trivy's
HTTP endpoint if any proxy is configured
Fixes #595
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>

Add Trivy to no_proxy configuration

---

templates/core/core-cm.yaml
templates/core/core-secret.yaml

Fixes #597, use the value of XSRF key in value.yaml if user set it

Use the value of XSRF key in value.yaml if user set it

---

templates/core/core-cm.yaml
templates/core/core-secret.yaml

Fixes #597, use the value of XSRF key in value.yaml if user set it

[Cherry-pick]Use the value of XSRF key in value.yaml if user set it

---

templates/trivy/trivy-sts.yaml

1. Make trivy work when persistence.enable is false.
2. Make trivy work with exist PVC.
Closes #596, #598

fix(trivy): make trivy work without persistence/with exist pvc

---

templates/_helpers.tpl
templates/trivy/trivy-sts.yaml
values.yaml

Without that option Core will not able to reach Trivy's
HTTP endpoint if any proxy is configured
Fixes #595
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>

[Cherry pick]Add Trivy to no_proxy configuration

---

README.md
templates/_helpers.tpl
templates/chartmuseum/chartmuseum-dpl.yaml
templates/clair/clair-dpl.yaml
templates/core/core-dpl.yaml
templates/jobservice/jobservice-dpl.yaml
templates/registry/registry-dpl.yaml
templates/trivy/trivy-sts.yaml
values.yaml

Add custom ca bundle support for chartmuseum, clair, core, jobservice,
registry and trivy components.
Closes #529

feat(ca-bundle): add custom ca bundle support

---

README.md
templates/_helpers.tpl
templates/chartmuseum/chartmuseum-dpl.yaml
templates/clair/clair-dpl.yaml
templates/core/core-dpl.yaml
templates/jobservice/jobservice-dpl.yaml
templates/registry/registry-dpl.yaml
templates/trivy/trivy-sts.yaml
values.yaml

Add custom ca bundle support for chartmuseum, clair, core, jobservice,
registry and trivy components.
Closes #529

[Cherry pick]feat(ca-bundle): add custom ca bundle support

---

templates/chartmuseum/chartmuseum-dpl.yaml
templates/clair/clair-dpl.yaml
templates/core/core-dpl.yaml
templates/database/database-ss.yaml
templates/jobservice/jobservice-dpl.yaml
templates/nginx/deployment.yaml
templates/notary/notary-server.yaml
templates/notary/notary-signer.yaml
templates/portal/deployment.yaml
templates/redis/statefulset.yaml
templates/registry/registry-dpl.yaml
templates/trivy/trivy-sts.yaml
values.yaml

To be able to assign custom PodSecurityPolicies or OpenShift's SCCs to all harbor's components I added a parameter to each component.
Default behavior is retrocompatible, so default serviceaccount is used if a specific one is not specified.
Thought about setting a general serviceaccount for all the deployments, but in my case it was better to have them split.
Fixes https://github.com/goharbor/harbor-helm/issues/560

Added customizable serviceAccountName for all components

---

templates/portal/deployment.yaml

The Chart can not be rendered due to whitespace removal
Introduced in #573, see the lint error report:
https://github.com/goharbor/harbor-helm/pull/573#issuecomment-639295313
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>

fix: helm lint reported issue

---

templates/trivy/trivy-sts.yaml

The StatefulSet for Trivy didn't have an imagePullSecret, making my deploy fail.

Add optional imagePullSecret to Trivy

---

templates/chartmuseum/chartmuseum-dpl.yaml

Needed for Chartmuseum to work with some S3 setups. I have only tested this on a self-hosted version of S3, so I can't speak for the "official" S3 servers.
See https://github.com/helm/chartmuseum/issues/280 for more details.

Chartmuseum: Set AWS_SDK_LOAD_CONFIG to make S3 work in more cases

---

Chart.yaml

Since the harbor documentation was moved from the official git repository, the icon specified in the `Chart.yaml` https://raw.githubusercontent.com/goharbor/harbor/master/docs/img/harbor_logo.png does not exist anymore. This pull request fixes this by using the harbor logo of a previous commit (which will also be a stable URL in the future).

fix Chart.yaml icon

---

templates/registry/registry-dpl.yaml

The registryctl container arguments are not used/needed.
Signed-off-by: Stefan Nica <snica@suse.com>

Remove unneeded args from registryctl container

---

README.md
docs/High Availability.md

Update the helm version to 2.10+ in doc as the sprig function "ternary" is introduced in 2.10

Update the helm version in doc

---

templates/registry/registry-cm.yaml

Convert the log level for registry as registry doesn't support warning and fatal

Convert the log level for registry

---

templates/core/core-cm.yaml

Add "CORE_LOCAL_URL" environment variable to make proxy cache work when internal TLS enabled

Add "CORE_LOCAL_URL" environment variable to make proxy cache work when internal TLS enabled

---

test/integration/node_port_test.go

The common name is changed to "expose.tls.auto.commonName", this PR update it

Set "expose.tls.auto.commonName" when serving with node port

---

templates/ingress/ingress.yaml

This PR is for update Ingress apiVersion from `extensions/v1beta1` to `networking.k8s.io/v1beta1` for supporting Kubernetes v1.16.
Closes #628 
Signed-off-by: Rodolfo Martínez <rodomar@outlook.com>

Update Ingress apiVersion for support Kubernetes v1.16

---

templates/ingress/ingress.yaml

The ingress-nginx 0.41.0 version changes the default `ImplementationSpecific`
`pathType` to adhere to the kubernetes ingress `pathType` specification [1].
The specification doesn't cover matching paths ending in a trailing `/`
for the `Prefix` `pathType`, which means trailing `/` must be removed.
[1] https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types
Fixes #783
Signed-off-by: Stefan Nica <snica@suse.com>

Fix ingress paths for ingress-nginx 0.41.0

---

docs/High Availability.md
docs/Upgrade.md
test/integration/base.go

1. Fix random CI failure in Github action
We install Harbor chart two times(one for testing ingress, the other one for testing node port) in the kind k8s cluster with the same release name "harbor", sometimes when running the testting for the node port, the service name "harbor-harbor-core" is resolved to the IP of service created in the testing for ingress. In this PR, we use different release names to avoid this
2. Refine some testing code
3. Update docs

Fix random CI failure in Github action

---

templates/core/core-dpl.yaml
values.yaml

Alternative to: https://github.com/goharbor/harbor-helm/pull/773
Instead try to detect a correct k8s version, just decide the user if they want to use startupProbes.
startupProbes are implement as Feature Gate but disabled by default since 1.16.
Since 1.18, `startupProbes` are enabled by default.
Using a strict `if version >= 1.18` check my help in general but users they enabled startupProbes in 1.16 could not benefit from.

Make startupProbe optional

---

templates/chartmuseum/chartmuseum-cm.yaml

Signed-off-by: Ziming Zhang <zziming@vmware.com>

[cherry-pick] fix(chartmuseum) compatible s3 cache fail for 1.5.2

---

templates/chartmuseum/chartmuseum-cm.yaml

some compatible s3 like DELL EMC s3 has some strange behavior that make the chart index cache not working
reference issue https://github.com/goharbor/harbor/issues/13592 and pr https://github.com/goharbor/harbor/pull/13600

fix(chartmuseum) compatible s3 cache fail

---

templates/notary/notary-server.yaml
templates/notary/notary-signer.yaml
values.yaml

This change moves the `podAnnotations`, `nodeSelector`, `affinity` and
`tolerations` from the notary level to the server and signer level.
This allows configuring those options specifically for the server or
signer deployments instead of using the same configuration for both.
Fixes: #789
Signed-off-by: Flávio Ramalho <framalho@suse.com>

Configure notary deployments at server/signer level

---

templates/chartmuseum/chartmuseum-dpl.yaml
templates/clair/clair-dpl.yaml
templates/core/core-dpl.yaml
templates/database/database-ss.yaml
templates/jobservice/jobservice-dpl.yaml
templates/notary/notary-server.yaml
templates/notary/notary-signer.yaml
templates/portal/deployment.yaml
templates/redis/statefulset.yaml
templates/registry/registry-dpl.yaml

Pods should not need the access to SA credentials.
Signed-off-by: Jiří Suchomel <jiri.suchomel@suse.com>
This solves https://github.com/goharbor/harbor-helm/issues/769

Disable mounting serviceAccount credentials from pods

---

README.md

The Readme references the key as `secretkey` but inside the chart it is used as `secretKey`. Note the capital **K**
see: https://github.com/goharbor/harbor-helm/blob/1acd0c7ef61c22ea90c877735517c5e6b7f10b17/templates/core/core-secret.yaml#L9

Typo in README wrong parameter name: secretkey -> secretKey

---

values.yaml

The helm chart here assumes annotations for nginx ingress, this PR clarifies changes may need to be made and gives an example of what to do for Envoy

update comments around ssl-redirect annotation for Envoy

---

templates/ingress/ingress.yaml

ApiVersion for Ingress resource is updated from /v1beta1 to /v1 in 1.19.
This patch set updates the version to suppress warning [0].
[0] W1214 16:05:27.903491 1293447 warnings.go:67] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Signed-off-by: Tin Lam <tin@irrational.io>

chore(vers): updates apiVersion for Ingress

---

templates/registry/registry-dpl.yaml

Remove the reference as this is a public key and registry will no longer
need it for token verification.
fixes #646

Remove the reference to "registry-root-certificate"

---

templates/core/core-cm.yaml

Enable proxy cache for more registries

Enable proxy cache for more registries

---

templates/registry/registry-cm.yaml

Render redis password in the config.yml of registry only when it's not
empty.

fix: render password in config.yml only it's not empty

---

.github/workflows/lint.yaml

Helm 2 is deprecated and will no longer be maintained after Nov 2020
[1]. The helm 2 linter already prevents some advanced features from
being used in the Harbor helm chart [2] and this will not be fixed.
This commit updates the helm 2 used by the linter to the latest
available version and makes the helm 2 linter check continue on failure.
[1] https://helm.sh/blog/helm-v2-deprecation-timeline/
[2] helm/helm#7955
Signed-off-by: Stefan Nica <snica@suse.com>

Bump helm 2 version for linter and allow helm 2 linter failures

---

.github/workflows/integration.yaml
templates/ingress/ingress.yaml

v1 Ingress requires changes in `rules` - so helm against k8s (e.g. 1.19.3 in my case) is failing.
This PR fixes it without updating integration test github action to test against k8s 1.19 as well.
Follow-up of #814.

Fix for networking.k8s.io/v1 Ingress

---

templates/ingress/ingress.yaml

Portal introduces a new file called "common.js", it is matched by the ingress rule of core "/c" which is mistake. This commit adds the suffix "/" for each rules to avoid such cases

Update ingress rules

---

templates/registry/registry-cm.yaml

docker registry and chartmuseum config endpoint syntax conflict
https://chartmuseum.com/docs/#using-with-alibaba-cloud-oss-storage
--storage-alibaba-endpoint="oss-cn-beijing.aliyuncs.com"
https://docs.docker.com/registry/storage-drivers/oss/?spm=5176.100239.blogcont7585.14.OScRv1
An endpoint which defaults to [bucket].[region].aliyuncs.com or [bucket].[region]-internal.aliyuncs.com (when internal=true). You can change the default endpoint by changing this value.

fix endpoint syntax conflict

---

.helmignore

Ignore the .github folder when packaging Harbor chart

---

.helmignore

[cherry-pick]Ignore the .github folder when packaging Harbor chart

---

README.md
templates/ingress/ingress.yaml
values.yaml

Hi,
This PR includes the changes to helm chart for allowing custom annotations separately for harbor and notary ingresses as opened with the issue #915 
Following structure is the way to use it:
```
ingress:
...
annotations: # common annotations for ingresses
harbor:
annotations: # custom annotations for harbor ingress
notary:
annotations: # custom annotations for notary ingress
```
Closes #915

add custom annotation support for harbor and notary ingresses

---

templates/nginx/configmap-http.yaml
templates/nginx/configmap-https.yaml

nginx configuration does not work when it's behind another proxy as noted in the comment in nginx's configmap:
```
proxy_set_header X-Forwarded-Proto $scheme;
```
I'm in that case where my haproxy already defines `X-Forwarded-Proto`, so I suggest reusing `X-Forwarded-Proto` if it's already defined instead of asking people "to remove the below line" ;)

handle nginx behind another proxy

---

templates/core/core-svc.yaml
templates/exporter/exporter-svc.yaml
templates/registry/registry-svc.yaml
templates/trivy/trivy-svc.yaml

If sevice port names are used, Istio expects the following convention: <protocol>[-<suffix>]
If the port names does not follow the convention, then istio is not able to route traffic properly.
Fixes #77
Signed-off-by: Jehoszafat Zimnowoda <jehoszafat.zimnowoda@redkubes.com>

Rename service ports for compatibility with istio.

---

templates/core/core-dpl.yaml
templates/database/database-ss.yaml
templates/jobservice/jobservice-dpl.yaml
templates/redis/statefulset.yaml
templates/registry/registry-dpl.yaml

Adds `terminationGracePeriodSeconds` to core, jobservice, registry,
redis and db pods to mitigate data corruption caused by force
termination.

Add terminationGracePeriodSeconds

---

templates/_helpers.tpl
templates/core/core-svc.yaml
templates/exporter/exporter-svc.yaml
templates/jobservice/jobservice-svc.yaml
templates/metrics/metrics-svcmon.yaml
templates/registry/registry-svc.yaml

Fix the mismatch in the portname between servicemonitor and services.

Fix the metric portname in servicemonitor

---

docs/Upgrade.md
templates/_helpers.tpl
test/integration/ingress_test.go

Updated to match all the currently generated helm fullname templates.

Use release name as full name if it contains chart name

---

templates/core/core-cm.yaml

Support "docker-registry" as the proxy cache registry

Support "docker-registry" as the proxy cache registry

---

.github/workflows/integration.yaml

Bump up kind version to 0.11.1 to avoid CI failure

Bump up kind version to avoid CI failure

---

.github/workflows/integration.yaml

Bump up kind version to 0.11.1 to avoid CI failure

[cherry-pick]Bump up kind version to avoid CI failure

---

test/e2e/Jenkinsfile

1. Pin jenkins shared library to version 2.4
2. Remove the setting for case branch as it is already pinned in the jenins shared library. Remove it so that we don't need to update it for every major release

Pin jenkins shared library to version 2.4

---

test/e2e/Jenkinsfile

Remove the setting for case branch as it is already pinned in the jenins shared library.

Remove the case branch setting

---

templates/ingress/ingress.yaml

According to the ingress specification [1], the longest matching path should
be used. But for Istio, "The first rule matching an incoming request is
used" [2],[3].
[1]: https://kubernetes.io/docs/concepts/services-networking/ingress/#multiple-matches
[2]: https://istio.io/latest/docs/reference/config/networking/virtual-service/#VirtualService
[3]: https://github.com/istio/istio/issues/35033
Fixes: #485
Signed-off-by: Mathieu Parent <math.parent@gmail.com>

Move portal at the end of the ingress paths

---

values.yaml

Corrects the comment mistake in the Jaeger support mode that has the `agent` and `collector` mode description the wrong way around.
Fixes #1164

Corrects comment mistake in Jaeger mode support

---

templates/ingress/ingress.yaml

the lack of trailing slash on /v2 path for default ingress cause ssl redirection trouble
if someone ask http://registry/v2/ redirect give https://registry/v2 who failed to authenticate

change v2 path for default ingress

---

templates/chartmuseum/chartmuseum-cm.yaml
templates/chartmuseum/chartmuseum-dpl.yaml
templates/chartmuseum/chartmuseum-secret.yaml
templates/registry/registry-dpl.yaml
templates/registry/registry-secret.yaml
values.yaml

In the GitOps world, it's a good practice to separate the configuration of secrets from the actual application Helm chart. 
Using secrets provisioned differently (for example with https://external-secrets.io/) makes it much easier to manage the lifecycle of a secret without the headache of "How would I securely inject my secret with Helm during CD?".
Although this PR only aims to fix that for the `persistence.imageChartStorage.s3` use case, it might encourage others to do the same for other `imageChartStorage` cases.

Add ability to configure an existing secret for S3 type storage

---

templates/chartmuseum/chartmuseum-cm.yaml

Add `AWS_INSECURE_SKIP_VERIFY` env variable to Chart Museum Config Map for support Self Signed S3-like Object Storage scenario
Fixes #1217

Add S3-like Self-signed Storage Backend support for Chart Museum

---

templates/notary/notary-secret.yaml
templates/notary/notary-server.yaml
templates/notary/notary-signer.yaml

This is a fix for #1263 that moves the DB_URLs into a secret instead of having them in plain text in the resource definitions.
Signed-off-by: Curt Cunning <curt.cunning@outlook.com>

Move the notary DB_URL strings into the notary-server secret

---

templates/registry/registry-dpl.yaml

Current code for specifying an existing secret for htpasswd in registry configuration doesn't work as expected due to missing `{{}}` to enable helm templating.
This change fixes this issue by adding `{{}}` to the respective parameter.

Harbor Registry -- Fix existing secret reference in deployment

---

templates/core/core-pre-upgrade-job.yaml

Fix: #1300
Add secret env to job when database external secret is used
Signed-off-by: Cong Ha Minh <conghm1@viettel.com.vn>
(cherry picked from commit 27f95dab3acd679c6bdfb58d6cc709ef0e5f74e0)

[Cherry-pick] Fix Helm Database Migration Job

---

templates/registry/registry-dpl.yaml

Fixes: #1309 
Add missing environment variable to registry container - only happens when using existingSecret for Azure imageChartStorage

Fix missing environment variable for registry container - Azure

---

templates/registry/registry-dpl.yaml

Fixes: #1309
Add missing environment variable to registry container - only happens when using existingSecret for Azure imageChartStorage
Signed-off-by: Raul Garcia Sanchez <info@raulgarcia.de>

[Cherry-pick] Fix missing environment variable for registry container - Azure

---

templates/core/core-cm.yaml

Add JFrog Artifactory As Supported Proxy-Cache Registry Source
Depends on https://github.com/goharbor/harbor/pull/17738 
Signed-off-by: Derrik Campau <dcampau@vmware.com>

Add JFrog Artifactory As Supported Proxy-Cache

---

templates/portal/deployment.yaml

There is a scenario from helm upgrade (for harbor upgrade/patch etc) with values changes that the configmap is not updated. This request is to add a support in portal/deployment to aware the configmap changes.

feat: add configmap checksum annotation for portal

---

templates/core/core-cm.yaml

fix: add github-ghcr to the list of PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE

---

templates/core/core-cm.yaml

[Cherry-pick] fix: add github-ghcr to the list of PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE

---

templates/metrics/metrics-svcmon.yaml

Removes the use of `.Capabilities` from the prometheus serviceMonitor. This allows things that utilize `helm template` or other similar tools to work.
Fixes #1127

Fix #1127 - remove capabilities check for prometheus

---

templates/registry/registry-dpl.yaml

If `persistence.imageChartStorage.s3.existingSecret` has been set, ensure the there is an envFrom secretRef for the `registryctl` container. This is already applied to the `registry` container.
Without this change when an existing S3 secret is used, garbage collection on an S3 bucket fails to successfully delete any blobs because the `registryctl` container has no valid S3 Auth available to it. 
The result of this issue is an ever growing S3 bucket that Harbor does not track because it has removed knowledge of the manifests/blobs during GC.

Add registryctl env secretRef for S3 existingSecret

---

templates/registry/registry-dpl.yaml

If s3.existingSecret has been set, ensure the there is an envFrom secretRef for the registryctl container
cherry-pick of PR: https://github.com/goharbor/harbor-helm/pull/1545

[Cherry-pick] Add registryctl env secretRef for S3 existingSecret

---

templates/_helpers.tpl
templates/registry/registry-dpl.yaml

cherry-pick of : https://github.com/goharbor/harbor-helm/pull/1607
fix: https://github.com/goharbor/harbor/issues/19387

fix external redis existing secret url render

---

.github/release.yml
.github/workflows/publish_release.yaml

1. Automating the release workflow
2. Release Notes Template

Add harbor-helm release workflow

---

templates/_helpers.tpl

fix: avoid decoding plain text password when database secret exists

---

templates/_helpers.tpl

[cherry-pick] fix: avoid decoding plain text password when database secret exists

---

templates/exporter/exporter-dpl.yaml

The exporter's `containerPort` should use `.Values.metrics.exporter.port`, not `harbor.core.containerPort`.

Fix the exporter's containerPort

---

templates/registry/registry-dpl.yaml

The registry's `containerPort` should use `.Values.metrics.registry.port` instead of `5001` if `.Values.metrics.enabled` is `true`.

Fix the registry's containerPort

---

templates/nginx/deployment.yaml

It is better to limit the nginx's `containerPort` and `port` to only those that are enabled.
`8443` is valid only if `.Values.expose.tls.enabled` is `true`.
`4443` is valid only if `.Values.expose.tls.enabled` and `.Values.notary.enabled` are both `true`.

Fix the nginx's containerPort

---

templates/_helpers.tpl
templates/core/core-dpl.yaml
templates/database/database-ss.yaml
templates/exporter/exporter-dpl.yaml
templates/jobservice/jobservice-dpl.yaml
templates/jobservice/jobservice-pvc.yaml
templates/nginx/deployment.yaml
templates/portal/deployment.yaml
templates/redis/statefulset.yaml
templates/registry/registry-dpl.yaml
templates/registry/registry-pvc.yaml
templates/trivy/trivy-sts.yaml

Adding recommended labels based on: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
Close #1704

Add recommended labels

---

values.yaml

The documentation link redirects to a not existing file anymore.

Fix dead documentation link in values.yaml

---

values.yaml

DOCS: missing link to distribution

---

templates/registry/registry-dpl.yaml

This patch removes the 'args' field from the 'registry-dpl' Deployment template, as is was completely ignored by the upstream registry-photon image's entrypoint.sh script which does not accept/process any arguments in any way.
Fixes: https://github.com/goharbor/harbor-helm/issues/1801

Remove ineffective 'args' from registry-dpl template.

---

templates/ingress/ingress.yaml

Hi,
I was hit by this, I see these errors in my ingress event logs
```
Warning  Translate  9m52s (x1702 over 7d7h)  loadbalancer-controller  Translation failed: invalid ingress spec: failed to validate prefix path /api/* due to invalid wildcard; failed to validate prefix path /service/* due to invalid wildcard; failed to validate prefix path /v2/* due to invalid wildcard; failed to validate prefix path /chartrepo/* due to invalid wildcard; failed to validate prefix path /c/* due to invalid wildcard; failed to validate prefix path /* due to invalid wildcard
```
I dug a bit and found #1620 and I figured these changes should fix the issue.

Fix issue #1620

---

.github/workflows/integration.yaml

update versions of
1, kind & kind-action
2, actions/checkout & upload-artifacts
3, ingress-controller
4, golang
5, kubernetes

fix ci failure

---

templates/nginx/configmap-http.yaml
templates/nginx/configmap-https.yaml

The chunk should be removed b/c it used to serve chart museum and it has been removed from Harbor

Remove chartrepo location for nginx configmap

---

values.yaml

fixed: https://github.com/goharbor/harbor-helm/issues/1847
per[ this comment](https://github.com/goharbor/harbor-helm/pull/1853#issuecomment-2488239728), will only add comment at the harbor-helm side.

add comment for CSRF key setting

---

templates/jobservice/jobservice-cm-env.yaml

Ensure `LOG_LEVEL` is set in the `harbor-jobservice-env` ConfigMap so that the `jobservice` correctly respects the `logLevel` value from `values.yaml`.
- Add `LOG_LEVEL` to the `harbor-jobservice-env` ConfigMap based on the `logLevel` field in `values.yaml`.
- Align the logging behavior of `jobservice` with that of `core`, which already respects the `LOG_LEVEL` environment variable.
Fixes #2166

Fix: fix bug where log level configuration was not applied

---

templates/database/database-ss.yaml
templates/redis/statefulset.yaml
templates/trivy/trivy-sts.yaml

As per https://github.com/goharbor/harbor-helm/issues/2174, adds the missing PVC manifest properties `apiVersion` and `kind`, so that ArgoCD can properly sync:
Symptoms:
Cause:
Fix: see [Files changed](https://github.com/goharbor/harbor-helm/pull/2173/files).

Fix ArgoCD sync
